Added translator for c++, may stop for now

diff --git a/projects/crossy/translate/test_all b/projects/crossy/translate/test_all
--- a/projects/crossy/translate/test_all
+++ b/projects/crossy/translate/test_all
@@ -1,9 +1,32 @@
+verbose=false
+
+while getopts ":v" opt; do
+  case $opt in
+    v)
+      verbose=true
+      ;;
+    \?)
+      echo "Invalid option: -$OPTARG" >&2
+      exit 1
+      ;;
+    :)
+      echo "Option -$OPTARG requires an argument." >&2
+      exit 1
+      ;;
+  esac
+done
+
 # set -x
 for p in $(find -name 'go.mod')
 do
     d="$(dirname ${p})"
     cd "$d"
-    go test ./...
+     
+    if $verbose; then
+        go test -v ./...
+    else
+        go test ./...
+    fi
     cd - &> /dev/null
 done
 # set +x
